### ISSUE TITLE
Map files cause Webpack warnings

### ISSUE THREAD

**Issue by UberMouse** [trialspark/enzyme-context#25]
**Describe the bug**
The map files that ship with the packages have a `src` reference to `../Src/fileName.ts`, because these files are not shipped with the package itself I am getting warnings from Webpack saying it can't find the file.

For now, I have ignored warnings like this but I would prefer not to do this as it could mask these warnings coming from our codebase which is not desirable. Would it be possible to get the map files updated to not include a `src` reference which does not exist?

**To Reproduce**
1. Run webpack build

**Screenshots**
![image](https://user-images.githubusercontent.com/693020/58996451-6848bc00-884c-11e9-8bf2-9caa71e69f0b.png)

**System information**
Webpack v4.30.0
Node v8.16

**Comment by naudo** [comment]
We are moving to archive this repo as we no longer support it and am closing this issue as "won't fix". 

If you're interested in maintaining this repo, please reach out!
