### ISSUE TITLE
Apollo mock fails if default resolver throws an error even if custom resolver resolves correctly

### ISSUE THREAD

**Issue by avmcrae** [trialspark/enzyme-context#43]
**Describe the bug**
If there is a default resolver passed into defaultMocks in the apollo context and then a custom resolver for the same query/entity is passed in upon mount of a component, when the default resolver throws an error, the error is raised in the test and the mocks fails to resolve, even if the custom resolver did not throw an error/returned a valid entity.

**To Reproduce**
1. Create a resolver that includes error handling such as:
```
const mockVisits = [{...someVisit, id: '1'}];
export const QueryResolverFactory = {
  visit: (visits = mockVisits): MockResolver<QueryResolvers['visit']> =>
     jest.fn(((_, args) => {
      const visit = visits.find((visit) => visit.id === args.id);

      if (!visit) {
        throw new Error('Visit not found');
      }

      return visit;
  }) as QueryResolvers['visit'])
};
```
2. Call this resolver as a default resolver with no arguments
```
defaultMocks: {
  Query: () => ({
    visit: QueryResolverFactory.visit()
  })
}
```
3. Pass a custom resolver into the `mount` call
```
const overridenVisit = {...someVisit, id: '20'};
component = mount(<Component />, {
  apolloMocks: {
          Query: () => ({
            visit: QueryResolverFactory.visit([overridenVisit])
         })
  }
})
```
4. An error will be thrown even though the structure of the visit in `const visit = {...someVisit, id: '20'}` is valid because visit id 20 was not found in mockVisits when the default resolver (from step 2) is called, even though the resolver in step 3 should work.

**Expected behavior**
`overridenVisit` should be returned from the mock.

**Comment by minznerjosh** [comment]
Fixed in #44!
